name: ci

on:
  pull_request:

jobs:
  trigger_semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh workflow run semgrep -f sha="${{ github.event.pull_request.head.sha }}"
        env:
          GH_TOKEN: ${{ github.token }}