name: semgrep

on:
  workflow_dispatch:
    inputs:
      sha:
        required: true

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}